# Avoid running not from project root(directory where compose.yaml is stored) as it causes docker to silently fail .env file load
services:
  discordgo:
    build: ./discordgo
    restart: ${DOCKER_RESTART_POLICY}
    environment:
      TOKEN: ${TOKEN}
    volumes:
      - ./discordgo:/app
    # FIXME: use internal docker network instead of exposing ports
    network_mode: host
    depends_on:
      - ollama
  ollama:
    build: ./ollama
    restart: ${DOCKER_RESTART_POLICY}
    ports:
      - 11434:11434
    volumes:
      - ./ollama:/root/.ollama
